
////////////////////////////////////////////
// Generated by BRCC 1.4
// BRCC Compiled on: Mar  2 2009 13:07:15
////////////////////////////////////////////

#include "brook/brook.h"
#include "NTLM_GPU_gpu.h"
#include "NTLM_GPU.h"

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
void  __gpu_ntlm_crypt_cpu_inner(const __BrtUInt1  &nt_buffer_0,
                                const __BrtUInt1  &nt_buffer_1,
                                const __BrtUInt1  &nt_buffer_2,
                                const __BrtUInt1  &nt_buffer_3,
                                const __BrtUInt1  &nt_buffer_4,
                                const __BrtUInt1  &nt_buffer_5,
                                const __BrtUInt1  &nt_buffer_6,
                                const __BrtUInt1  &nt_buffer_7,
                                const __BrtUInt1  &nt_buffer_8,
                                const __BrtUInt1  &nt_buffer_9,
                                const __BrtUInt1  &nt_buffer_10,
                                const __BrtUInt1  &nt_buffer_11,
                                const __BrtUInt1  &nt_buffer_12,
                                const __BrtUInt1  &nt_buffer_13,
                                const __BrtUInt1  &nt_buffer_14,
                                const __BrtUInt1  &nt_buffer_15,
                                __BrtUInt1  &output_0,
                                __BrtUInt1  &output_1,
                                __BrtUInt1  &output_2,
                                __BrtUInt1  &output_3)

#line 6 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
{

#line 7 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __BrtUInt1  a = (__BrtUInt1 ) (__BrtInt1((int)0x67452301));

#line 8 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __BrtUInt1  b = (__BrtUInt1 ) (__BrtInt1((int)0xefcdab89));

#line 9 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __BrtUInt1  c = (__BrtUInt1 ) (__BrtInt1((int)0x98badcfe));

#line 10 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __BrtUInt1  d = (__BrtUInt1 ) (__BrtInt1((int)0x10325476));

#line 12 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __BrtUInt1  SQRT_2 = (__BrtUInt1 ) (__BrtInt1((int)0x5a827999));

#line 13 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __BrtUInt1  SQRT_3 = (__BrtUInt1 ) (__BrtInt1((int)0x6ed9eba1));


#line 15 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ b & (c ^ d)) + nt_buffer_0;

#line 15 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 16 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ a & (b ^ c)) + nt_buffer_1;

#line 16 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)7) | d >> __BrtInt1((int)25);

#line 17 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ d & (a ^ b)) + nt_buffer_2;

#line 17 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 18 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ c & (d ^ a)) + nt_buffer_3;

#line 18 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)19) | b >> __BrtInt1((int)13);

#line 20 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ b & (c ^ d)) + nt_buffer_4;

#line 20 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 21 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ a & (b ^ c)) + nt_buffer_5;

#line 21 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)7) | d >> __BrtInt1((int)25);

#line 22 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ d & (a ^ b)) + nt_buffer_6;

#line 22 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 23 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ c & (d ^ a)) + nt_buffer_7;

#line 23 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)19) | b >> __BrtInt1((int)13);

#line 25 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ b & (c ^ d)) + nt_buffer_8;

#line 25 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 26 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ a & (b ^ c)) + nt_buffer_9;

#line 26 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)7) | d >> __BrtInt1((int)25);

#line 27 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ d & (a ^ b)) + nt_buffer_10;

#line 27 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 28 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ c & (d ^ a)) + nt_buffer_11;

#line 28 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)19) | b >> __BrtInt1((int)13);

#line 30 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ b & (c ^ d)) + nt_buffer_12;

#line 30 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 31 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ a & (b ^ c)) + nt_buffer_13;

#line 31 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)7) | d >> __BrtInt1((int)25);

#line 32 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ d & (a ^ b)) + nt_buffer_14;

#line 32 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 33 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ c & (d ^ a)) + nt_buffer_15;

#line 33 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)19) | b >> __BrtInt1((int)13);

#line 36 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (b & (c | d) | c & d) + nt_buffer_0 + SQRT_2;

#line 36 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 37 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (a & (b | c) | b & c) + nt_buffer_4 + SQRT_2;

#line 37 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)5) | d >> __BrtInt1((int)27);

#line 38 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (d & (a | b) | a & b) + nt_buffer_8 + SQRT_2;

#line 38 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)9) | c >> __BrtInt1((int)23);

#line 39 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (c & (d | a) | d & a) + nt_buffer_12 + SQRT_2;

#line 39 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)13) | b >> __BrtInt1((int)19);

#line 41 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (b & (c | d) | c & d) + nt_buffer_1 + SQRT_2;

#line 41 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 42 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (a & (b | c) | b & c) + nt_buffer_5 + SQRT_2;

#line 42 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)5) | d >> __BrtInt1((int)27);

#line 43 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (d & (a | b) | a & b) + nt_buffer_9 + SQRT_2;

#line 43 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)9) | c >> __BrtInt1((int)23);

#line 44 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (c & (d | a) | d & a) + nt_buffer_13 + SQRT_2;

#line 44 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)13) | b >> __BrtInt1((int)19);

#line 46 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (b & (c | d) | c & d) + nt_buffer_2 + SQRT_2;

#line 46 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 47 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (a & (b | c) | b & c) + nt_buffer_6 + SQRT_2;

#line 47 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)5) | d >> __BrtInt1((int)27);

#line 48 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (d & (a | b) | a & b) + nt_buffer_10 + SQRT_2;

#line 48 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)9) | c >> __BrtInt1((int)23);

#line 49 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (c & (d | a) | d & a) + nt_buffer_14 + SQRT_2;

#line 49 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)13) | b >> __BrtInt1((int)19);

#line 51 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (b & (c | d) | c & d) + nt_buffer_3 + SQRT_2;

#line 51 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 52 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (a & (b | c) | b & c) + nt_buffer_7 + SQRT_2;

#line 52 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)5) | d >> __BrtInt1((int)27);

#line 53 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (d & (a | b) | a & b) + nt_buffer_11 + SQRT_2;

#line 53 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)9) | c >> __BrtInt1((int)23);

#line 54 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (c & (d | a) | d & a) + nt_buffer_15 + SQRT_2;

#line 54 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)13) | b >> __BrtInt1((int)19);

#line 57 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ c ^ b) + nt_buffer_0 + SQRT_3;

#line 57 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 58 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ b ^ a) + nt_buffer_8 + SQRT_3;

#line 58 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)9) | d >> __BrtInt1((int)23);

#line 59 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ a ^ d) + nt_buffer_4 + SQRT_3;

#line 59 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 60 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ d ^ c) + nt_buffer_12 + SQRT_3;

#line 60 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)15) | b >> __BrtInt1((int)17);

#line 62 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ c ^ b) + nt_buffer_2 + SQRT_3;

#line 62 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 63 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ b ^ a) + nt_buffer_10 + SQRT_3;

#line 63 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)9) | d >> __BrtInt1((int)23);

#line 64 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ a ^ d) + nt_buffer_6 + SQRT_3;

#line 64 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 65 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ d ^ c) + nt_buffer_14 + SQRT_3;

#line 65 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)15) | b >> __BrtInt1((int)17);

#line 67 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ c ^ b) + nt_buffer_1 + SQRT_3;

#line 67 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 68 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ b ^ a) + nt_buffer_9 + SQRT_3;

#line 68 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)9) | d >> __BrtInt1((int)23);

#line 69 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ a ^ d) + nt_buffer_5 + SQRT_3;

#line 69 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 70 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ d ^ c) + nt_buffer_13 + SQRT_3;

#line 70 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)15) | b >> __BrtInt1((int)17);

#line 72 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a += (d ^ c ^ b) + nt_buffer_3 + SQRT_3;

#line 72 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  a = a << __BrtInt1((int)3) | a >> __BrtInt1((int)29);

#line 73 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d += (c ^ b ^ a) + nt_buffer_11 + SQRT_3;

#line 73 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  d = d << __BrtInt1((int)9) | d >> __BrtInt1((int)23);

#line 74 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c += (b ^ a ^ d) + nt_buffer_7 + SQRT_3;

#line 74 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  c = c << __BrtInt1((int)11) | c >> __BrtInt1((int)21);

#line 75 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b += (a ^ d ^ c) + nt_buffer_15 + SQRT_3;

#line 75 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  b = b << __BrtInt1((int)15) | b >> __BrtInt1((int)17);

#line 77 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  output_0 = a + (__BrtUInt1 ) (__BrtInt1((int)0x67452301));

#line 78 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  output_1 = b + (__BrtUInt1 ) (__BrtInt1((int)0xefcdab89));

#line 79 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  output_2 = c + (__BrtUInt1 ) (__BrtInt1((int)0x98badcfe));

#line 80 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  output_3 = d + (__BrtUInt1 ) (__BrtInt1((int)0x10325476));
}
void  __gpu_ntlm_crypt_cpu(::brt::KernelC *__k, int __brt_idxstart, int __brt_idxend, bool __brt_isreduce)

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
{

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_0 = (::brt::StreamInterface *) __k->getVectorElement(0);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_1 = (::brt::StreamInterface *) __k->getVectorElement(1);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_2 = (::brt::StreamInterface *) __k->getVectorElement(2);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_3 = (::brt::StreamInterface *) __k->getVectorElement(3);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_4 = (::brt::StreamInterface *) __k->getVectorElement(4);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_5 = (::brt::StreamInterface *) __k->getVectorElement(5);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_6 = (::brt::StreamInterface *) __k->getVectorElement(6);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_7 = (::brt::StreamInterface *) __k->getVectorElement(7);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_8 = (::brt::StreamInterface *) __k->getVectorElement(8);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_9 = (::brt::StreamInterface *) __k->getVectorElement(9);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_10 = (::brt::StreamInterface *) __k->getVectorElement(10);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_11 = (::brt::StreamInterface *) __k->getVectorElement(11);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_12 = (::brt::StreamInterface *) __k->getVectorElement(12);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_13 = (::brt::StreamInterface *) __k->getVectorElement(13);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_14 = (::brt::StreamInterface *) __k->getVectorElement(14);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_nt_buffer_15 = (::brt::StreamInterface *) __k->getVectorElement(15);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_output_0 = (::brt::StreamInterface *) __k->getVectorElement(16);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_output_1 = (::brt::StreamInterface *) __k->getVectorElement(17);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_output_2 = (::brt::StreamInterface *) __k->getVectorElement(18);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brt::StreamInterface *arg_output_3 = (::brt::StreamInterface *) __k->getVectorElement(19);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    for(int __brt_idx=__brt_idxstart; __brt_idx<__brt_idxend; __brt_idx++) {
  if(!(__k->isValidAddress(__brt_idx))){ continue; }

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    Addressable <__BrtUInt1  > __out_arg_output_0((__BrtUInt1 *) __k->FetchElem(arg_output_0, __brt_idx));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    Addressable <__BrtUInt1  > __out_arg_output_1((__BrtUInt1 *) __k->FetchElem(arg_output_1, __brt_idx));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    Addressable <__BrtUInt1  > __out_arg_output_2((__BrtUInt1 *) __k->FetchElem(arg_output_2, __brt_idx));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    Addressable <__BrtUInt1  > __out_arg_output_3((__BrtUInt1 *) __k->FetchElem(arg_output_3, __brt_idx));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    __gpu_ntlm_crypt_cpu_inner (

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_0, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_1, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_2, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_3, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_4, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_5, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_6, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_7, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_8, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_9, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_10, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_11, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_12, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_13, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_14, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                Addressable <__BrtUInt1 >((__BrtUInt1 *) __k->FetchElem(arg_nt_buffer_15, __brt_idx)),

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                __out_arg_output_0,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                __out_arg_output_1,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                __out_arg_output_2,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
                                __out_arg_output_3);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    *reinterpret_cast<__BrtUInt1 *>(__out_arg_output_0.address) = __out_arg_output_0.castToArg(*reinterpret_cast<__BrtUInt1 *>(__out_arg_output_0.address));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    *reinterpret_cast<__BrtUInt1 *>(__out_arg_output_1.address) = __out_arg_output_1.castToArg(*reinterpret_cast<__BrtUInt1 *>(__out_arg_output_1.address));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    *reinterpret_cast<__BrtUInt1 *>(__out_arg_output_2.address) = __out_arg_output_2.castToArg(*reinterpret_cast<__BrtUInt1 *>(__out_arg_output_2.address));

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
    *reinterpret_cast<__BrtUInt1 *>(__out_arg_output_3.address) = __out_arg_output_3.castToArg(*reinterpret_cast<__BrtUInt1 *>(__out_arg_output_3.address));
  }
}

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
void __gpu_ntlm_crypt::operator()(const ::brook::Stream< uint >& nt_buffer_0,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_1,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_2,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_3,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_4,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_5,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_6,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_7,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_8,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_9,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_10,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_11,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_12,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_13,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_14,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream< uint >& nt_buffer_15,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream<  uint >& output_0,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream<  uint >& output_1,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream<  uint >& output_2,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
		const ::brook::Stream<  uint >& output_3)
{

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  static const void *__gpu_ntlm_crypt_fp[] = {

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
     "cal", __gpu_ntlm_crypt_cal,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
     "cpu", (void *) __gpu_ntlm_crypt_cpu,

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
     NULL, NULL };


#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  ::brook::Kernel  __k(__gpu_ntlm_crypt_fp, brook::KERNEL_MAP);
  ::brook::ArgumentInfo __argumentInfo;


#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_0);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_1);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_2);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_3);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_4);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_5);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_6);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_7);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_8);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_9);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_10);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_11);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_12);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_13);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_14);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushStream(nt_buffer_15);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushOutput(output_0);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushOutput(output_1);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushOutput(output_2);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __k.PushOutput(output_3);

#line 4 "c:/lavernasbrute_local/msvc/lavernasbrute/NTLM_GPU.br"
  __argumentInfo.startExecDomain = _domainOffset;
  __argumentInfo.domainDimension = _domainSize;


  __k.run(&__argumentInfo);
  DESTROYPARAM();

}

__THREAD__ __gpu_ntlm_crypt gpu_ntlm_crypt;


